# TASK-2

## If Else 

In [1]:
## if condition

a=10;b=20

if(a>5):
    print("a is greater than 5")
if(b>10):
    print("a is greater than 10")
if(a>10):
    print("a is greater than 10")

a is greater than 5
a is greater than 10


In [2]:
## The elif keyword is Python's way of saying "if the previous conditions were not true,
## then try this condition".

if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")

b is greater than a


In [3]:
## The else keyword catches anything which isn't caught by the preceding conditions.

a=33;b=22

if(a==10):
    print("a is",a)
else:
    print("else statement is printed")


else statement is printed


#### Short Hand If

In [4]:
## If you have only one statement to execute, you can put it on the same line as the if statement

a=33;b=22

if a > b: print("a is greater than b")

a is greater than b


#### Short Hand If ... Else

In [5]:
## If you have only one statement to execute, one for if, and one for else,
## you can put it all on the same line:

a=33;b=22

print("b is greater") if (b>a)  else print("a is greater")

a is greater


In [6]:
## You can also have multiple else statements on the same line:

a=33;b=22

print("b is greater") if(b>a) else print("a is equal to b") if(a==b) else print("a is greater")

a is greater


In [7]:
## AND,OR,NOT keywords are a logical operator

a=10;b=20;c=10

if (a==10) and (a>9):
    print("Both conditions are True")
    
if (b==20 or c>10):
    print("At least one of the condition is true")
    
if not a>b:
    print("a is lesser than b")

Both conditions are True
At least one of the condition is true
a is lesser than b


In [8]:
## Lets try to combine 'and','or' and 'not' keywords

if (b==20 or c>10) and not(a>b):
    print("combinations of 'and','or'and 'not'keywords ")
    
# b==20 or c>10 is true
# not(a>b) is true
# hence and of these true are true

combinations of 'and','or'and 'not'keywords 


#### The pass Statement

In [9]:
a=11;b=22

if(b>a):
    pass
else:
    print("a is greater")

## While Loop

In [10]:
## With the while loop we can execute a set of statements as long as a condition is true.

i=1
while(i<5):
    print(i)
    i+=1

1
2
3
4


#### The break Statement

In [11]:
## With the break statement we can stop the loop even if the while condition is true:

i = 1
while i < 5:
  print(i)
  if i == 3:
    break
  i += 1

1
2
3


#### The continue Statement

In [12]:
##With the continue statement we can stop the current iteration, and continue with the next:

i = 0
while i < 5:
  i += 1
  if i == 3:
    continue
  print(i)

1
2
4
5


#### The else Statement

In [13]:
## With the else statement we can run a block of code once when the condition no longer is true:

i = 1
while i < 5:
  print(i)
  i += 1
else:
  print("i is no longer less than 5")

1
2
3
4
i is no longer less than 5


## Functions

In [14]:
## In Python a function is defined using the def keyword:

def trial_function():
    print("function statement")

In [15]:
## to call function call its name with paranthese

trial_function()

function statement


In [16]:
## Arguments
##Information can be passed into functions as arguments

def my_function(fname):
  print(fname + " Ravikumar")

my_function("karthikaa")
my_function("nimitha")

karthikaa Ravikumar
nimitha Ravikumar


In [17]:
def add(a,b):
    print("{0} + {1} = {2}".format(a,b,a+b))
add(2,4)
add(4,5)

add(2) 

#  if your function expects 2 arguments, you have to call the function with 2 arguments,
#  not more, and not less.

2 + 4 = 6
4 + 5 = 9


TypeError: add() missing 1 required positional argument: 'b'

# TASK 3.1

#### Arbitrary Arguments

In [18]:
## If the number of arguments is unknown, add a * before the parameter name:

def greatest(*num):
    i=0
    result=0

    while(i<len(num)):
        if(num[i] > num[i]+1):
           result=num[i]
        else:
            result=num[i]+1
        i+=1
    return result
    

print("The greatest number is ",greatest(1,2,3,4,5))

The greatest number is  6


#### Default value can be followed by Arbitrary argument

In [19]:
def my_function(*kid,country="india"):
  print("His last name is " + kid[1] + " and from " + country)

my_function("Tobias","Refsnes")

His last name is Refsnes and from india


In [20]:
def my_function(country="india",*kid):
  print("His last name is " + kid[1] + " and from " + country)

my_function("Tobias","Refsnes")

# the error is because as it is positional argument 'Tobias' is assigned to country and the kid
# tuple is now with one element in it,here comes "index error" will calling the tuple's 2nd 
# element.

IndexError: tuple index out of range

In [ ]:
# Let us add one more argument in the function see what happens

def my_function(country="india",*kid):
  print("His last name is " + kid[1] + " and from " + country)

my_function("Tobias","Refsnes","karu")

# Now "Tobias" is assigned to country and the remaining ("Refsnes","karu") tuple 
# is assigned to kid. When calling kid[1], there comes karu.

#### Keyword Arguments

In [21]:
## You can also send arguments with the key = value syntax
## even the order is changed that doesn't matter,whatever the key called will reflect with its 
## value assigned inside the function

def my_function(child3, child2, child1):
  print("The youngest child is " + child3)

my_function(child1 = "Emil", child2 = "Tobias", child3 = "Linus")

The youngest child is Linus


#### Arbitrary Keyword Arguments

In [22]:
def my_function(**kid):
  print("His last name is " + kid["lname"])

my_function(lname="Tobias",fname="Refsnes")

His last name is Tobias


In [23]:
def my_function(**kid,country="india"):
  print("His last name is " + kid["lname"] +"and from "+ country)

my_function(lname="Tobias",fname="Refsnes")

SyntaxError: invalid syntax (2756281501.py, line 1)

#### Default Parameter Value

In [24]:
def attendance(name,attend="absent"):
    print(name,"is",attend)
    
attendance("karthika","present")
attendance("nimitha","present")
attendance("rathi")

karthika is present
nimitha is present
rathi is absent


In [25]:
def attendance(attend="absent",name):
    print(name,"is",attend)
    
attendance("karthika","present")
attendance("nimitha","present")
attendance("rathi")

SyntaxError: non-default argument follows default argument (4114999170.py, line 1)

In [26]:
def attendance(name,attend="absent",status="good"):
    print(name,"is",attend,"and is",status)
    
attendance("karthika","present","good")
attendance("nimitha","present","bad")
attendance("rathi",,"bad")       ## we should use key-word to solve this error

SyntaxError: invalid syntax (2753762713.py, line 6)

In [27]:
 ## we should use key-word to solve this error as shown below:
    
 def attendance(name,attend="absent",status="good"):
    print(name,"is",attend,"and is",status)
    
attendance("karthika","present","good")
attendance("nimitha","present","bad")
attendance("rathi",status="bad")     

karthika is present and is good
nimitha is present and is bad
rathi is absent and is bad


# TASK 3.2

## Copy and view

In [28]:
import numpy as np

In [29]:
ls=[x for x in range(5)]

In [30]:
ls

[0, 1, 2, 3, 4]

In [31]:
arr1=np.array(ls)

In [32]:
arr1

array([0, 1, 2, 3, 4])

In [33]:
x=arr1.copy()
y=arr1.view()

In [34]:
print("Original: ",arr1)
print("----------------")
print("Copy:     ",x)
print("----------------")
print("View:     ",y)

Original:  [0 1 2 3 4]
----------------
Copy:      [0 1 2 3 4]
----------------
View:      [0 1 2 3 4]


In [35]:
## changing the value in original

arr1[1]=100

print("Original: ",arr1)
print("----------------")
print("Copy:     ",x)
print("----------------")
print("View:     ",y)

## Both view and original are changed with  no change in copy

Original:  [  0 100   2   3   4]
----------------
Copy:      [0 1 2 3 4]
----------------
View:      [  0 100   2   3   4]


In [36]:
## changing the value in the view

y[0]=50

print("Original: ",arr1)
print("----------------")
print("Copy:     ",x)
print("----------------")
print("View:     ",y)

## Both view and original are changed with  no change in copy

Original:  [ 50 100   2   3   4]
----------------
Copy:      [0 1 2 3 4]
----------------
View:      [ 50 100   2   3   4]


In [37]:
## changing the value in the copy

x[2]=150

print("Original: ",arr1)
print("----------------")
print("Copy:     ",x)
print("----------------")
print("View:     ",y)

## Only the copy value change,but original and view are unchanged

Original:  [ 50 100   2   3   4]
----------------
Copy:      [  0   1 150   3   4]
----------------
View:      [ 50 100   2   3   4]


# TASK 3.3
#### List comprehension filter

In [38]:
from numpy import random

In [39]:
age = np.array([i for i in random.randint(50, size = 10)])
age

array([ 7, 41, 42, 33, 49, 20,  7, 45, 24, 16])

In [40]:
check_bool=age[[True if i>=18 else False for i in age ]]
check_bool

array([41, 42, 33, 49, 20, 45, 24])