# Numpy Arrays

In [1]:
import numpy as np

In [2]:
## Array without numpy
my_list = [1,4,8]
my_list

[1, 4, 8]

In [3]:
## Array using numpy
list = np.array(my_list)
list

array([1, 4, 8])

## 2-D array

In [78]:
TwoD = np.array([[1,2,3],[4,5,6]])
TwoD

array([[1, 2, 3],
       [4, 5, 6]])

## 3-D array

In [79]:
ThreeD = np.array([[1,2,3],[4,5,6],[7,8,9]])
ThreeD

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
print(np.arange(2,12))   # get values from 2-11
print(np.arange(2,21,2)) # get even values from 2-20 as step value is 2
print(np.arange(20,1,-1)) #Descending order/reverse

[ 2  3  4  5  6  7  8  9 10 11]
[ 2  4  6  8 10 12 14 16 18 20]
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2]


### zeros()  and ones()

In [81]:
## Creating dimentional array filled with zeros

print(np.zeros(3)) # 1D with three values

[0. 0. 0.]


In [82]:
print(np.zeros(5)) #1D with 5 values

[0. 0. 0. 0. 0.]


In [83]:
print(np.zeros((1,3))) #2D with 1 rows, 3 colums

[[0. 0. 0.]]


In [84]:
print(np.zeros((6,3))) #2D with 6 rows, 3 colums

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [85]:
## Creating dimentional array filled with ones

print(np.ones(3)) # 1D with three values

[1. 1. 1.]


In [86]:
print(np.ones(5)) #1D with 5 values

[1. 1. 1. 1. 1.]


In [87]:
print(np.ones((1,3))) #2D with 1 rows, 3 colums

[[1. 1. 1.]]


In [88]:
print(np.ones((6,3))) #2D with 6 rows, 3 colums

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### linspace() and eye()

In [89]:
#  used to create an evenly spaced sequence in a specified interval.

np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [90]:
np.linspace(2,20,10)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [91]:
# eye - create 2D square matrix (rows = columns)
# Leading diagnol values are 1 , upper and lower triangle values are 0

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [92]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

## Random

### rand() - gives uniformly distributed numbers

In [93]:
np.random.rand(5)

array([0.11084791, 0.56586477, 0.6207786 , 0.27315014, 0.47624613])

In [94]:
np.random.rand(2,2)

array([[0.03995165, 0.68580689],
       [0.01166237, 0.50798559]])

### randn() - gives ununiformly distributed numbers

In [95]:
np.random.randn(2)

array([-0.29584915,  1.6708584 ])

In [96]:
np.random.randn(2,2)

array([[-0.0424635 , -0.27214843],
       [ 0.4918671 , -2.17206847]])

### randint() - gives random number between the range

In [97]:
np.random.randint(0,200,10)

array([108,  76, 109,  75,  61, 138, 103, 173, 196,  67])

In [98]:
np.random.randint(0,5,3)

## randint may repeats value

array([3, 0, 3])

## reshape()

In [99]:
arr = np.random.randint(0,20,10)
arr1 = np.arange(25)

In [100]:
arr.reshape(5,2)

array([[ 7,  2],
       [ 4, 10],
       [15,  7],
       [12, 19],
       [ 7, 11]])

In [101]:
arr1.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## Basic methods

In [102]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [103]:
arr1.max()

24

In [104]:
arr1.min()

0

In [105]:
np.average(arr1)

12.0

In [106]:
np.mean(arr1)

12.0

In [107]:
arr1.argmax()

## shows the index value

24

In [108]:
arr1.argmin()

0

In [109]:
arr1.shape

(25,)

In [110]:
reshaped = arr1.reshape(5,5)

In [111]:
reshaped.shape

(5, 5)

In [112]:
arr.dtype

dtype('int64')

Instead of typing entire (np.random.randint()), we can import the randint and use it as shown below

In [113]:
from numpy.random import randint

In [114]:
randint(0,200,10)

array([114, 115,  44,  13, 102,  30,  45,  73, 191,  10])

## copy() and view()

In [142]:
a1 = np.arange(1,6)
a1

array([1, 2, 3, 4, 5])

In [143]:
# copying a1 array and storing it in a variable named 'copy'

copy = a1.copy()
copy

array([1, 2, 3, 4, 5])

In [144]:
copy[0]

1

In [145]:
#changing value of copy[0] (i.e 1) into '100'

copy[0] = 100
copy

array([100,   2,   3,   4,   5])

In [146]:
# now checking whether, it is also changed in the original array 'a1'
a1

array([1, 2, 3, 4, 5])

RESULT : NO, copy() does not reflect on the original array.

In [147]:
view = a1.view()

In [149]:
view

array([1, 2, 3, 4, 5])

In [150]:
#changing value of view[0] (i.e 1) into '100'

view[0] = 100
view

array([100,   2,   3,   4,   5])

In [151]:
# now checking whether, it is also changed in the original array 'a1'
a1

array([100,   2,   3,   4,   5])

RESULT : NO, view() does reflect on the original array.

## INDEXING AND SELECTION

1D

In [126]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [127]:
arr[8]

8

In [128]:
arr[1:11]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
arr[2:6]

array([2, 3, 4, 5])

In [47]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr[:3]

array([0, 1, 2])

In [49]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
## reverse
arr[-1:-11:-1]

## can be also written as arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [59]:
arr[0:5] = 789
arr

## can replace the assigned value with the value in the sliced range of array

array([789, 789, 789, 789, 789,   5,   6,   7,   8,   9,  10])

In [60]:
a = np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
slice = a[1:9]
slice

array([1, 2, 3, 4, 5, 6, 7, 8])

In [62]:
slice[:] = 60
slice

array([60, 60, 60, 60, 60, 60, 60, 60])

In [64]:
a

array([ 0, 60, 60, 60, 60, 60, 60, 60, 60,  9, 10])

RESULT = numpy does view() and not copy() the array to save space.

## 2D

In [186]:
_2D = np.array([randint(20,30,5),randint(30,40,5),randint(40,50,5)])
_2D

array([[25, 29, 27, 26, 28],
       [30, 36, 34, 30, 36],
       [43, 44, 45, 41, 45]])

In [187]:
_2D.shape

(3, 5)

In [188]:
_2D[0]

array([25, 29, 27, 26, 28])

In [189]:
_2D[1]

array([30, 36, 34, 30, 36])

In [190]:
_2D[0][0]

25

In [224]:
_2D[1,3]

30

In [193]:
_2D[1][4]

36

In [210]:
_2D[:2]

array([[25, 29, 27, 26, 28],
       [30, 36, 34, 30, 36]])

In [206]:
_2D

array([[25, 29, 27, 26, 28],
       [30, 36, 34, 30, 36],
       [43, 44, 45, 41, 45]])

In [205]:
_2D[0:3,1:3]

array([[29, 27],
       [36, 34],
       [44, 45]])

In [207]:
_2D[0:1,0:1]

array([[25]])

In [209]:
_2D[1:3,2:4]

array([[34, 30],
       [45, 41]])

BOOL values

In [212]:
age = np.arange(0,20)
age

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [217]:
age > 18

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True])

In [218]:
eligible = age >= 18
age[eligible]

array([18, 19])

Create 2D in different ways

ONE:

In [219]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

TWO:

In [221]:
arr2 = np.arange(50).reshape(10,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

## ARRAY OPERATIONS

In [234]:
_1 = np.arange(1,6)
_2 = np.arange(6,11)
_1

array([1, 2, 3, 4, 5])

In [235]:
_1 + _1

array([ 2,  4,  6,  8, 10])

In [236]:
_1 + _2

array([ 7,  9, 11, 13, 15])

In [237]:
_1 * _2

array([ 6, 14, 24, 36, 50])

In [238]:
_1 * 100

array([100, 200, 300, 400, 500])

In [239]:
_2 / _1

array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ])

In [241]:
_2 - 1

array([5, 6, 7, 8, 9])

In [245]:
a = np.arange(0,3)
a / a

## leads to error as 0 cannot be dived by zero. It gives a null value.

<ipython-input-245-b94ae517ced5>:2: RuntimeWarning: invalid value encountered in true_divide
  a / a


array([nan,  1.,  1.])

In [246]:
np.divide(0,0)

<ipython-input-246-20851cc7e1db>:1: RuntimeWarning: invalid value encountered in true_divide
  np.divide(0,0)


nan

In [247]:
np.divide(1,0)

<ipython-input-247-c72f3a3aa847>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(1,0)


inf

In [248]:
_1 ** 2

array([ 1,  4,  9, 16, 25])

In [267]:
np.sqrt(81)

9.0

In [268]:
# creating an array with square values of numbers from 1 to 10
# and findkng the square root of those numbers
sq = np.array([x*x for x in range(2,11)])
np.sqrt(sq)

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [317]:
## Cube root

np.cbrt(27)

3.0000000000000004

In [269]:
#exponential

np.exp(2)

7.38905609893065

In [274]:
# Logarithm

np.log(10)

2.302585092994046

In [270]:
np.sin(100)

-0.5063656411097588

In [271]:
np.cos(100)

0.8623188722876839

In [272]:
np.tan(100)

-0.5872139151569291

In [275]:
np.add(1,2)

3

In [276]:
np.subtract(3,2)

1

In [277]:
np.multiply(6,6)

36

In [278]:
np.divide(81,9)

9.0

In [284]:
n = [10,34,-19,-87]
np.negative(n)

array([-10, -34,  19,  87])

In [285]:
np.positive(n)

array([ 10,  34, -19, -87])

In [286]:
np.remainder(3,2)

1

In [288]:
np.mod(5,6)

5

In [290]:
divmod(6,4)

## '1' is my quotient and '2' is my remainder when 6/4

(1, 2)

In [291]:
divmod(4,5)

## '0' is my quotient and '4' is my remainder when 4/5

(0, 4)

In [295]:
# change all elements into absolute value

np.fabs(n)

array([10., 34., 19., 87.])

In [296]:
## round off the values

np.rint(99.99999)

100.0

In [312]:
np.rint(5.499999999999999)

## '14' 19's

5.0

In [313]:
np.rint(5.4999999999999999)

## '15' 19's

6.0

In [315]:
## returns based on -ve or +ve

np.sign(n)

array([ 1,  1, -1, -1])

In [319]:
np.gcd(24,6)

6

In [323]:
np.lcm(2476723,69372)

171815227956